# Generated by Django 2.1.4 on 2018-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_dt',
            field=models.DateField(),
        ),
    ]
