# Generated by Django 2.1.4 on 2018-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='now',
            field=models.BooleanField(default=False),
        ),
    ]
