# Generated by Django 2.1.4 on 2018-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20181230_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Description', models.TextField(default='')),
                ('date', models.DateField()),
                ('url', models.TextField()),
            ],
        ),
    ]
