# Generated by Django 2.1.4 on 2018-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20181230_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='company',
            field=models.CharField(default='', max_length=150),
        ),
    ]
