# Generated by Django 2.1.4 on 2018-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20181231_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='award',
            field=models.BooleanField(default=False, help_text='Check if this is award'),
        ),
    ]
