# Generated by Django 2.1.4 on 2018-12-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Blog', max_length=40)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(help_text='Blog post', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
